#!/usr/bin/env bash

install_ansible() {
	if [[ -z $(command -v ansible-playbook) ]]; then
		sudo apt install ansible -y
	fi
}

if [[ -z $1 ]]; then
	echo "usage: install [option]"
	echo ""
	echo "options:"
	echo ""
	echo "  personal        install everything"
	echo "  work            install all work tasks"
	echo "  vm              install all work tasks minus kitty"
	echo "  dev             install zsh,nvim,tmux,fzf"
	echo "  container       build a docker dev container"
	echo "  test [tag]      install tasks with specified tag"
elif [[ $1 == "work" ]]; then
	install_ansible
	ansible-playbook main.yml -i localhost, -K --tags "dotfiles,zsh,tmux,nvim,node,docker,python,gnome,kitty,i3,git"
elif [[ $1 == "vm" ]]; then
	install_ansible
	ansible-playbook main.yml -i localhost, -K --tags "dotfiles,zsh,tmux,nvim,node,docker,python,gnome,i3,git"
elif [[ $1 == "container" ]]; then
	docker build -t "ansible" .
	echo ""
	echo "Dev container built. Run using:"
	echo "docker run --rm -it ansible"
elif [[ $1 == "dev" ]]; then
	install_ansible
	ansible-playbook main.yml -i localhost, -K --tags "dotfiles,zsh,tmux,nvim,node,git"
elif [[ $1 == "personal" ]]; then
	install_ansible
	ansible-playbook main.yml -i localhost, -K
elif [[ $1 == "test" ]]; then
	install_ansible
	ansible-playbook main.yml -i localhost, -K --tags "$2"
else
	echo "Invalid option."
	echo ""
	./"$0"
fi
