---
- name: Install Development Environment
  hosts: localhost
  connection: local
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update-cache: true
        state: present
      tags:
        - zsh
        - nvim
        - dotfiles
        - gnome
        - docker
        - kitty
        - i3
        - python
  tasks:
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh.yml
    - include: tasks/tmux.yml
    - include: tasks/nvim.yml
    - include: tasks/gnome.yml
    - include: tasks/docker.yml
    - include: tasks/python.yml
    # - include: tasks/i3.yml
    # - include: tasks/kitty.yml

# TODO: add macOS support
# TODO: add command line options with charm cli tools
# TODO: add option to install kitty or use Gnome terminal
# TODO: add option to install i3



# TODO: add spotify
# TODO: add gimp
