---
- name: Install Development Environment
  hosts: localhost
  connection: local
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update-cache: true
        state: present
      tags:
        - zsh
        - nvim
        - dotfiles
        - gnome
        - docker
  tasks:
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh.yml
    - include: tasks/tmux.yml
    - include: tasks/nvim.yml
    - include: tasks/plugins.yml
    - include: tasks/gnome.yml
    - include: tasks/docker.yml
