---
- name: Install Development Environment
  hosts: localhost
  connection: local
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update-cache: true
        state: present
      tags:
        - always

  tasks:
    - name: Install
      block:
        - include: tasks/core.yml
        - include: tasks/dotfiles.yml
        - include: tasks/zsh.yml
        - include: tasks/tmux.yml
        - include: tasks/nvim.yml
        - include: tasks/node.yml
        - include: tasks/docker.yml
        - include: tasks/python.yml
        - include: tasks/gnome.yml
        - include: tasks/kitty.yml
        - include: tasks/spotify.yml
        - include: tasks/gimp.yml
        - include: tasks/i3.yml

# TODO: add macOS support
