---
- name: Install Development Environment
  hosts: localhost
  connection: local
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: Update cache
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update-cache: true
        state: present
      tags:
        - always

  tasks:
    - name: Setup Ubuntu
      when: ansible_facts["distribution"] == "Ubuntu"
      block:
        - name: Core
          ansible.builtin.import_tasks: tasks/core.yml
          tags:
            - always

        - name: Dotfiles
          ansible.builtin.import_tasks: tasks/dotfiles.yml
          tags:
            - dotfiles

        - name: Zsh
          ansible.builtin.import_tasks: tasks/zsh.yml
          tags:
            - zsh

        - name: Fzf
          ansible.builtin.import_tasks: tasks/fzf.yml
          tags:
            - fzf
            - dotfiles
            - zsh
            - nvim

        - name: Tmux
          ansible.builtin.import_tasks: tasks/tmux.yml
          tags:
            - tmux

        - name: Nvim
          ansible.builtin.import_tasks: tasks/nvim.yml
          tags:
            - nvim

        - name: Node
          ansible.builtin.import_tasks: tasks/node.yml
          tags:
            - node

        - name: Docker
          ansible.builtin.import_tasks: tasks/docker.yml
          tags:
            - docker

        - name: Python
          ansible.builtin.import_tasks: tasks/python.yml
          tags:
            - python

        - name: Gnome
          ansible.builtin.import_tasks: tasks/gnome.yml
          tags:
            - gnome

        - name: Kitty
          ansible.builtin.import_tasks: tasks/kitty.yml
          tags:
            - kitty

        - name: Spotify
          ansible.builtin.import_tasks: tasks/spotify.yml
          tags:
            - spotify

        - name: Gimp
          ansible.builtin.import_tasks: tasks/gimp.yml
          tags:
            - gimp

        - name: I3
          ansible.builtin.import_tasks: tasks/i3.yml
          tags:
            - i3
# TODO: add macOS support
# TODO: add task for kubectl/minikube
