- name: Install Packages
  become: true
  apt:
    name:
      - unzip
      - curl
      - ca-certificates
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"
      
- name: Install i3
  become: true
  apt:
    name:
      - i3
      - picom
    state: present
  tags:
    - i3
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install kitty
  become: true
  apt:
    name:
      - kitty
    state: present
  tags:
    - kitty
  when: ansible_facts["distribution"] == "Ubuntu"
