- name: Install System Packages 1 (npm,unzip,ripgrep)
  become: true
  apt:
    name: ["ripgrep","npm","unzip"]
  tags:
    - nvim
      
- name: Install System Packages 2 (stow,fzf,i3,picom)
  become: true
  apt:
    name: ["stow","fzf","i3","picom"]
  tags:
    - dotfiles
