- name: Install Packages
  become: true
  apt:
    name:
      - unzip
      - curl
      - ca-certificates
      - make
    state: present
  tags:
    - always
  when: ansible_facts["distribution"] == "Ubuntu"
