- name: Install Packages
  become: true
  ansible.builtin.apt:
    name:
      - unzip
      - curl
      - ca-certificates
      - make
    state: present

- name: Install Utils
  become: true
  ansible.builtin.apt:
    name:
      - xclip
    state: present
