- name: Install Core Utilities
  become: true
  apt:
    name:
      - ripgrep
      - npm
      - unzip
      - curl
    state: present
  tags:
    - nvim
      
- name: Install Core Utilities
  become: true
  apt:
    name:
      - stow
      - fzf
      - i3
      - picom
    state: present
  tags:
    - dotfiles
