- name: Install Core Utilities
  become: true
  apt:
    name:
      - ripgrep
      - npm
      - unzip
      - curl
      - ca-certificates
    state: present
  tags:
    - nvim
  when: ansible_facts["distribution"] == "Ubuntu"
      
- name: Install Core Utilities
  become: true
  apt:
    name:
      - stow
      - fzf
      - i3
      - picom
    state: present
  tags:
    - dotfiles
  when: ansible_facts["distribution"] == "Ubuntu"
