- name: Install dotfiles dependencies
  become: true
  ansible.builtin.apt:
    name:
      - fzf
      - stow
      - fontconfig
      - make
    state: present

- name: Download dotfiles # noqa latest
  ansible.builtin.git:
    repo: https://github.com/joey-bednar/dotfiles
    dest: "{{ home_dir }}/dotfiles"
    clone: true
    update: true
    force: true

- name: Make update dotfiles
  ansible.builtin.shell: |
    cd {{ home_dir }}/dotfiles
    make update

- name: Load kitty.conf
  ansible.builtin.shell: |
    cd {{ home_dir }}/dotfiles
    make setup

- name: Reload fonts
  ansible.builtin.shell: |
    fc-cache -f -v

- name: Create personal directory
  ansible.builtin.file:
    path: "{{ home_dir }}/personal"
    state: directory
    mode: "0755"

- name: Create work directory
  ansible.builtin.file:
    path: "{{ home_dir }}/work"
    state: directory
    mode: "0755"
