- name: Download dotfiles
  git:
    repo: https://github.com/joey-bednar/dotfiles
    dest: "{{ home_dir }}/dotfiles"
    clone: yes
    update: yes
    force: yes
  tags:
    - dotfiles
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Load kitty.conf
  shell: |
    bash {{home_dir}}/dotfiles/setup
  tags:
    - dotfiles
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Stow dotfiles
  shell: |
    rm {{ home_dir }}/.zshrc
    rm {{ home_dir }}/.tmux.conf
    cd {{ home_dir }}/dotfiles
    stow .
  tags:
    - dotfiles
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Reload fonts
  shell: |
    fc-cache -f -v
  tags:
    - dotfiles
  when: ansible_facts["distribution"] == "Ubuntu"

