- name: Download fzf # noqa latest
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ home_dir }}/.fzf"
    clone: true
    update: true
    force: true

- name: Install fzf
  become: true
  ansible.builtin.shell: |
    cd {{ home_dir }}
    ./.fzf/install --all --no-bash --no-fish
  changed_when: true
