- name: Download fzf # noqa latest
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ home_dir }}/.fzf"
    clone: true
    update: true
    force: true

- name: Install fzf
  ansible.builtin.shell: |
    .fzf/install
  changed_when: true
