- name: Set Wallpaper
  shell: |
    gsettings set org.gnome.desktop.background picture-uri file://{{ home_dir }}/ansible/ubuntu-background.jpg
  tags:
    - gnome
  when: ansible_facts["distribution"] == "Ubuntu"
