- name: Install i3
  become: true
  apt:
    name:
      - i3
      - i3wm
      - i3status
      - i3lock
      - i3blocks
      - picom
    state: present
  tags:
    - i3
  when: ansible_facts["distribution"] == "Ubuntu"
