- name: Install i3
  become: true
  apt:
    name:
      - i3
      - picom
      - feh
      - acpi
      - brightnessctl
    state: present
  tags:
    - i3

- name: Modify brightnessctl permissions
  become: true
  shell: |
    chmod +s $(which brightnessctl)
  tags:
    - i3

