- name: Install nvim dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - fzf
      - npm
      - curl
      - cargo
      - python3.10-venv
    state: present

- name: Check if nvim.appimage exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/nvim.appimage"
  register: nvim_appimage_status

- name: Download Nvim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dest: "{{ home_dir }}/nvim.appimage"
    mode: "u+x"

- name: Check if nvim in bin
  ansible.builtin.stat:
    path: "/usr/bin/nvim"
  register: nvim_status

- name: Install nvim
  become: true
  ansible.builtin.shell: |
    cd {{ home_dir }}
    {{ home_dir }}/nvim.appimage --appimage-extract
    mv {{ home_dir }}/squashfs-root /
    rm /usr/bin/nvim
    ln -s /squashfs-root/AppRun /usr/bin/nvim
  when: not nvim_status.stat.exists
  changed_when: not nvim_status.stat.exists

- name: Check if nvim dotfiles exist
  ansible.builtin.stat:
    path: "{{ home_dir }}/dotfiles"
  register: dotfiles_status

- name: Install Neovim Plugins
  ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
  when: dotfiles_status.stat.exists
  changed_when: dotfiles_status.stat.exists
