- name: Install Nvim
  shell: |
    curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o {{ home_dir }}/nvim.appimage
    chmod u+x ~/nvim.appimage
    cd {{ home_dir }}
    ~/nvim.appimage --appimage-extract
  tags:
    - nvim

- name: Expose Nvim globally
  become: true
  shell: |
    mv {{ home_dir }}/squashfs-root /
    ln -s /squashfs-root/AppRun /usr/bin/nvim
  tags:
    - nvim

- name: Install Packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ home_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    clone: yes
    update: yes
  tags:
    - nvim
