- name: Install nvim dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - fzf
      - npm
      - curl
      - cargo
      - python3.10-venv
    state: present

- name: Check if nvim.appimage exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/nvim.appimage"
  register: nvim_appimage_status

- name: Install Nvim # noqa no-changed-when
  ansible.builtin.shell: |
    curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o {{ home_dir }}/nvim.appimage
    chmod u+x ~/nvim.appimage
    cd {{ home_dir }}
    ~/nvim.appimage --appimage-extract
  when: not nvim_appimage_status.stat.exists

- name: Check if nvim in bin
  ansible.builtin.stat:
    path: "/usr/bin/nvim"
  register: nvim_status

- name: Expose Nvim globally # noqa no-changed-when
  become: true
  ansible.builtin.shell: |
    mv {{ home_dir }}/squashfs-root /
    rm /usr/bin/nvim
    ln -s /squashfs-root/AppRun /usr/bin/nvim
  when: not nvim_status.stat.exists

- name: Check if nvim dotfiles exist
  ansible.builtin.stat:
    path: "{{ home_dir }}/dotfiles"
  register: dotfiles_status

- name: Install Neovim Plugins
  ansible.builtin.shell: nvim --headless "+Lazy! sync" +qa
  when: dotfiles_status.stat.exists
