- name: Install python packages
  become: true
  apt:
    name:
      - python3
      - python3-pip
    state: present
  tags:
    - python
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Check if anaconda is installed
  stat:
    path: "{{ home_dir }}/anaconda3"
  register: anaconda_status
  tags:
    - python
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install anaconda
  become: true
  shell: |
    curl -o anaconda.sh https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh
    chmod +x anaconda.sh
    ./anaconda.sh -b -p {{ home_dir }}/anaconda3
    ln -s {{ home_dir }}/anaconda3/bin/conda /usr/bin/conda
    mv {{ home_dir }}/anaconda3/bin/clear {{ home_dir }}/anaconda3/bin/clear_old
    conda config --set auto_activate_base false
    conda deactivate
  tags:
    - python
  when: not anaconda_status.stat.exists and ansible_facts["distribution"] == "Ubuntu"
