- name: Install python packages
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Check if anaconda is installed
  ansible.builtin.stat:
    path: "{{ home_dir }}/anaconda3"
  register: anaconda_status

- name: Install anaconda
  become: true
  ansible.builtin.shell: |
    cd {{ home_dir }}
    curl -o anaconda.sh https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh
    chmod +x anaconda.sh
    ./anaconda.sh -b -p {{ home_dir }}/anaconda3
    ln -s {{ home_dir }}/anaconda3/bin/conda /usr/bin/conda
    mv {{ home_dir }}/anaconda3/bin/clear {{ home_dir }}/anaconda3/bin/clear_old
    rm {{ home_dir }}/anaconda.sh
  when: not anaconda_status.stat.exists
  changed_when: not anaconda_status.stat.exists

- name: Check if dotfiles exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/dotfiles"
  register: dotfiles_status

- name: Use dotfiles .condarc
  ansible.builtin.shell: |
    cd {{ home_dir }}/dotfiles
    make update
  when: not anaconda_status.stat.exists and dotfiles_status.stat.exists
  changed_when: not anaconda_status.stat.exists and dotfiles_status.stat.exists
