- name: Install python packages
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
  tags:
    - python

- name: Check if anaconda is installed
  become: true
  ansible.builtin.stat:
    path: "opt/anaconda3/bin/conda"
  register: anaconda_status
  tags:
    - python

- name: Install anaconda
  become: true
  ansible.builtin.shell: |
    cd {{ home_dir }}
    curl -o anaconda.sh https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh
    chmod +x anaconda.sh
    ./anaconda.sh -b -p /opt/anaconda3
    ln -s /opt/anaconda3/bin/conda /usr/bin/conda
    mv /opt/anaconda3/bin/clear /opt/anaconda3/bin/clear_old
    rm {{ home_dir }}/anaconda.sh
  when: not anaconda_status.stat.exists
  changed_when: not anaconda_status.stat.exists
  tags:
    - python

- name: Check if dotfiles exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/dotfiles"
  register: dotfiles_status
  tags:
    - python

- name: Use dotfiles .condarc
  ansible.builtin.shell: |
    cd {{ home_dir }}/dotfiles
    make update
    make setup
  when: not anaconda_status.stat.exists and dotfiles_status.stat.exists
  changed_when: not anaconda_status.stat.exists and dotfiles_status.stat.exists
  tags:
    - python
