- name: Install spotify
  become: true
  snap:
    name:
      - spotify
    state: present

- name: Add spotify to favorites
  ansible.builtin.shell: |
    gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop','firefox_firefox.desktop','kitty.desktop','spotify_spotify.desktop']"
