- name: Install tmux
  become: true
  apt: name=tmux
  tags:
    - tmux
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install Tmux Plugin Manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "~/.tmux/plugins/tpm"
    clone: yes
    update: yes
  tags:
    - tmux
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install Tmux Plugins
  shell: |
    tmux start-server
    tmux new-session -d
    {{ home_dir }}/.tmux/plugins/tpm/scripts/install_plugins.sh
    tmux kill-server
  tags:
    - tmux
  when: ansible_facts["distribution"] == "Ubuntu"
