- name: Install tmux
  become: true
  apt:
    name:
      - tmux
    state: present
  tags:
    - tmux
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install Tmux Plugin Manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "~/.tmux/plugins/tpm"
    clone: yes
    update: yes
  tags:
    - tmux
  when: ansible_facts["distribution"] == "Ubuntu"
