- name: Install tmux
  become: true
  ansible.builtin.apt:
    name:
      - tmux
    state: present

- name: Install Tmux Plugin Manager # noqa latest
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
    clone: true
    update: true
