- name: Install zsh
  become: true
  apt: name=zsh
  tags:
    - zsh

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ home_dir }}/.oh-my-zsh"
  tags:
    - zsh

- name: Set zsh to default shell
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"
  become: true
  tags:
    - zsh

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    clone: yes
    update: yes
  tags:
    - zsh

- name: Install zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes
  tags:
    - zsh
