- name: Install zsh
  become: true
  apt: name=zsh
  tags:
    - zsh

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ home_dir }}/.oh-my-zsh"
  tags:
    - zsh
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Set zsh as default shell
  become: true
  shell: chsh -s $(which zsh) {{ username }}
  tags:
    - zsh

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    clone: yes
    update: yes
  tags:
    - zsh
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes
  tags:
    - zsh
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Check if dotfiles exists
  stat:
    path: "{{ home_dir }}/dotfiles"
  register: dotfiles_status
  tags:
    - zsh
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Use dotfiles .zshrc
  shell: |
    rm {{ home_dir }}/.zshrc
    cd {{ home_dir }}/dotfiles
    stow .
  tags:
    - zsh
  when: dotfiles_status.stat.exists and ansible_facts["distribution"] == "Ubuntu"
